import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { MICROSOFT_BOOKINGS_URL } from '@/lib/bookings'
import { Calendar, EnvelopeSimple } from '@phosphor-icons/react'

const bookingNotes = ['Organization and role', 'Day-to-day task under consideration', 'Current ChatGPT Work or Codex status', 'Information sensitivity']

export function ContactPage() {
  return <div className="min-h-screen bg-white pt-24 text-[#282523]"><div className="mx-auto max-w-[1180px] px-5 py-16 sm:px-6 lg:px-8">
    <div className="mb-14 max-w-3xl"><p className="font-mono text-xs uppercase tracking-[0.18em] text-[#8b817a]">Regulated day-to-day enterprise tasks</p><h1 className="mb-5 mt-4 font-serif text-4xl font-normal leading-tight text-[#343230] lg:text-5xl">Discuss a Agentic AI Integration and Risk Management</h1><p className="text-lg leading-8 text-[#67615d]">A 30-minute working conversation for enterprise teams considering a Workspace AI Compliance Audit. It determines whether the paid audit is appropriate; it is not a free audit.</p></div>
    <div className="grid gap-10 lg:grid-cols-3"><div className="lg:col-span-2"><Card className="rounded-md border-[#d9dedb] p-8 shadow-[0_18px_55px_rgba(37,31,28,0.06)]"><div className="max-w-2xl"><h2 className="mb-3 font-serif text-3xl font-normal leading-tight text-[#343230]">Plan Your AI Adoption Audit</h2><p className="mb-6 leading-7 text-[#67615d]">Use the existing booking link to choose a time. Include a few notes so the conversation can focus on the right day-to-day task, controls, and decision path.</p><div className="mb-8 grid gap-3 text-sm leading-6 text-[#67615d] sm:grid-cols-2">{bookingNotes.map((item) => <div key={item} className="rounded-md bg-[#f7f8f5] p-3">{item}</div>)}</div><div className="flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="rounded-full bg-[#193a42] px-6 hover:bg-[#102b32]"><a href={MICROSOFT_BOOKINGS_URL} target="_blank" rel="noopener noreferrer">Plan Your AI Adoption Audit</a></Button><Button asChild size="lg" variant="outline" className="rounded-full border-[#ded8d2] px-6"><a href="mailto:partnerships@dockio.in">Email partnerships@dockio.in</a></Button></div></div></Card></div>
      <div className="space-y-6"><Card className="rounded-md border-[#d9dedb] p-6 shadow-none"><h3 className="mb-4 font-semibold text-[#282523]">Direct contact</h3><div className="space-y-4 text-sm"><div className="flex items-start gap-3"><EnvelopeSimple className="mt-0.5 h-5 w-5 text-[#1f6d73]" /><div><p className="mb-1 font-medium text-[#282523]">Email</p><a href="mailto:partnerships@dockio.in" className="text-[#67615d] transition-colors hover:text-[#1f6d73]">partnerships@dockio.in</a></div></div><div className="flex items-start gap-3"><Calendar className="mt-0.5 h-5 w-5 text-[#1f6d73]" /><div><p className="mb-1 font-medium text-[#282523]">AI adoption audit</p><a href={MICROSOFT_BOOKINGS_URL} target="_blank" rel="noopener noreferrer" className="text-[#67615d] transition-colors hover:text-[#1f6d73]">Plan Your AI Adoption Audit</a></div></div></div></Card>
        <Card className="rounded-md border-none bg-[#f7f8f5] p-6 shadow-none"><h3 className="mb-3 font-semibold text-[#282523]">What happens next</h3><ol className="space-y-3 text-sm leading-6 text-[#67615d]">{['We review the day-to-day task context you share.', 'We use the 30 minutes to test Workspace AI Compliance Audit fit.', 'We confirm whether the paid audit is the right next step.', 'Pilot or implementation work is scoped separately after the audit.'].map((item, index) => <li key={item} className="flex gap-2"><span className="font-semibold text-[#1f6d73]">{index + 1}.</span><span>{item}</span></li>)}</ol></Card></div>
    </div>
  </div></div>
}
